[package]
name = "change-git-user"
version = "0.0.1"
authors = ["Spenser Black <spenserblack01@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A tool to switch git user"
readme = "README.md"
keywords = ["git"]
categories = ["command-line-utilities"]
repository = "https://github.com/spenserblack/change-git-user"
publish = false # You should at least look at this file before you publish

[dependencies]
